### ISSUE TITLE
Désactiver shorturls ?

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#107]
```curid`` a déjà été retiré de https://shakepeers.org/index.php?title=Modèle:BandeauHeaderPublication , eg https://shakepeers.org/Publication:Les_piafs_ont-ils_du_pif_%3F_Le_cas_des_rapaces

**Comment by Rudloff** [comment]
Rien d'autre à faire a priori, c'est pas un plugin.
