### ISSUE TITLE
Améliorer l'empreinte écologique du site

### ISSUE THREAD

**Issue by Rudloff** [ShakePeers/shakepeers-mediawiki#108]
http://www.ecoindex.fr/resultats/?id=5881

Pas trop mal mais les pages sont encore un peu lourdes.

**Comment by vbonhomme** [comment]
cool ce serait presque un truc qu'on pourrait mettre en avant ds le footer ou autre

**Comment by Rudloff** [comment]
J'ai fait du tri dans les polices qu'on charge mais je peux pas faire grand chose de plus dans l'immédiat.
C'est surtout le CSS de MediaWiki qui est lourd.
