### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#11]
Je pense qu'on aura besoin de : 
* auteur(s)
* contributeurs
* éditeur(s)
* date révision
* nb révisions
* date publication

Techniquement, on peut en déduire certaines. Une piste pour implémenter: [Variables](http://www.mediawiki.org/wiki/Extension:Variables)

**Comment by Rudloff** [comment]
On a ce qui faut maintenant pour ça, non ?
