### ISSUE TITLE
Tweets automatiques

### ISSUE THREAD

**Issue by Rudloff** [ShakePeers/shakepeers-mediawiki#30]
Pour twetter lorsqu'un nouvel article est publié, par exemple.

**Comment by vbonhomme** [comment]
Pourrait-on mettre en place un twitter de modifs, pour la phase de lancement, ça peut être sympatoche ?

**Comment by Rudloff** [comment]
Ça risque de spammer beaucoup quand on fait plein de petites corrections. Un tweet groupé (e.g. « 15 modifications dans la dernière heure sur... ») peut être, mais je ne sais pas si c'est possible.

**Comment by vbonhomme** [comment]
ça ça serait le top de chez top

Le 11 janvier 2015 18:02, Pierre Rudloff <notifications@github.com> a écrit
:

> Ça risque de spammer beaucoup quand on fait plein de petites corrections.
> Un tweet groupé (e.g. « 15 modifications dans la dernière heure sur... »)
> peut être, mais je ne sais pas si c'est possible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/30#issuecomment-69503901>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
faudrait penser à une logique de digest aussi, hebdos / journaliers /
mensuels, à balancer par mail sur une liste ddiée

Le 11 janvier 2015 18:04, Vincent Bonhomme <bonhomme.vincent@gmail.com> a
écrit :

> ça ça serait le top de chez top
>
> Le 11 janvier 2015 18:02, Pierre Rudloff <notifications@github.com> a
> écrit :
>
>> Ça risque de spammer beaucoup quand on fait plein de petites corrections.
>> Un tweet groupé (e.g. « 15 modifications dans la dernière heure sur... »)
>> peut être, mais je ne sais pas si c'est possible.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ShakePeers/MediaKiki/issues/30#issuecomment-69503901>
>> .
>>
>
>
>
> --
> vincentbonhomme.fr <http://www.vincentbonhomme.fr>
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by PaX80000** [comment]
Hello, tweetter ce genre d'informations ne me parait pas très intéressant (pour ne pas dire totalement contre-productif en termes de communication :o)). Par contre tweeter automatiquement les derniers articles, oui, c'est une très bonne idée.

**Comment by Rudloff** [comment]
Je pense qu'on peut utiliser l'extension [News](https://www.mediawiki.org/wiki/Extension:News) pour générer un flux RSS avec ce qu'on veut puis après le balancer à Twitter/FB.

**Comment by Rudloff** [comment]
Vu la faible activité de note compte Twitter et du wiki, je ferme pour l'instant.
