### ISSUE TITLE
Spécial:Téléverser

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#31]
Faudrait expliciter [ici](https://shakepeers.org/Sp%C3%A9cial:T%C3%A9l%C3%A9verser)

**Comment by vbonhomme** [comment]
Par ailleurs, dans l'aide, [page médias](https://shakepeers.org/Aide:M%C3%A9dias) je fais désormais apparaître l'option commons (qu'on avait dit privilégier, autant que possible) + téléverser.

**Comment by Rudloff** [comment]
Nickel :)
