### ISSUE TITLE
Statistiques de visites

### ISSUE THREAD

**Issue by Rudloff** [ShakePeers/shakepeers-mediawiki#35]
Il faudrait installer Piwik ou un truc du genre pour savoir combien de visiteurs on a.

**Comment by vbonhomme** [comment]
voué. et aussi une dérivée du compteur sur la page d'accueil, par articles, notamment ceux en révision, serait précieuse.

**Comment by Rudloff** [comment]
=> utiliser le Piwik d'Animafac
