### ISSUE TITLE
Quid de Flow

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#44]
https://www.mediawiki.org/wiki/Flow ?

**Comment by Rudloff** [comment]
C'est pas encore stable, il faudra attendre au moins la prochaine version de MediaWiki.

**Comment by vbonhomme** [comment]
va bene

2015-02-17 15:27 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> C'est pas encore stable, il faudra attendre au moins la prochaine version
> de MediaWiki.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/44#issuecomment-74675162>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Ça a l'air beaucoup trop galère de passer le LiquidThreads à Flow.
