### ISSUE TITLE
DPL

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#46]
Il serait génial de pouvoir afficher la date quand on fait du order = created. [DPL]([https://www.mediawiki.org/wiki/Extension:DynamicPageList_%28Wikimedia%29#Order) pour sorter par date ici, et permet d'afficher joliment pour l'argument "addfirstcategorydate", mais pas pour order tout court.

voir https://shakepeers.org/Publication & https://shakepeers.org/Révision

**Comment by Rudloff** [comment]
Tu voudrais prendre quelle date du coup ? La date de création de l'article ?

**Comment by vbonhomme** [comment]
le top serait de pouvoir choisir date de passage p ou r / date création /
date dernière modif.
avec par défaut date de passage en révision / puiblication

:~)

2015-02-22 22:02 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> Tu voudrais prendre quelle date du coup ? La date de création de l'article
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/46#issuecomment-75457700>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Il faudrait le proposer aux développeurs de DPL du coup : https://phabricator.wikimedia.org/tag/mediawiki-extensions-dynamicpagelist/

**Comment by Rudloff** [comment]
Bon date de passage en révision/publication ça me parait chaud à faire. Mais date de denière modification ça être faisable.
