### ISSUE TITLE
Ajouter "Contributions"

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#48]
Sur les pages utilisateur (dans le (i) ), serait bien pratique.
Limite associé à la signature ici et là (façon c-d-m dans Wikipedia)

**Comment by Rudloff** [comment]
J'ai adapté le modèle de Wikipédia : https://shakepeers.org/Mod%C3%A8le:U
Je vais voir pour ajouter Contributions dans le menu Informations.

**Comment by CarolAnnO** [comment]
Merci !

**Comment by Rudloff** [comment]
J'ai rajouté ça sur beta : https://beta.shakepeers.org/Utilisateur:Rudloff

**Comment by vbonhomme** [comment]
que faut il voir ?

2016-05-23 0:14 GMT+02:00 Pierre Rudloff <notifications@github.com>:

> J'ai rajouté ça sur beta : https://beta.shakepeers.org/Utilisateur:Rudloff
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/48#issuecomment-220859830>
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Le bouton _Contributions_ dans le menu _Outils_.

**Comment by vbonhomme** [comment]
coool

2016-05-24 10:24 GMT+02:00 Pierre Rudloff <notifications@github.com>:

> Le bouton *Contributions* dans le menu *Outils*.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/48#issuecomment-221199759>
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
