### ISSUE TITLE
encadré à droite des articles

### ISSUE THREAD

**Issue by CarolAnnO** [ShakePeers/shakepeers-mediawiki#50]
Est-ce que l'on ne pourrait pas supprimer l'encadré à droite des articles regroupant les infos (contributeurs, dernières motifs et date de création) + autres articles dans la même catégorie (?)

Les premières infos sont pertinentes (contributeurs, dernières motifs et date de création) mais ne pourrait-on pas les mettre en fin d'articles. Pour les "autres lectures", je pense que c'est lié à une catégorie, du coup la catégorie (par exemple : Biologie) est déjà indiquée en fin d'articles. 

Je pense que cela serait plus esthétique et clair. 

Merci, bisou

**Comment by vbonhomme** [comment]
viré via https://shakepeers.org/MediaWiki:Common.css l'infobox.

Le 14 mars 2015 16:48, CarolAnnO <notifications@github.com> a écrit :

> Est-ce que l'on ne pourrait pas supprimer l'encadré à droite des articles
> regroupant les infos (contributeurs, dernières motifs et date de création)
> + autres articles dans la même catégorie (?)
>
> Les premières infos sont pertinentes (contributeurs, dernières motifs et
> date de création) mais ne pourrait-on pas les mettre en fin d'articles.
> Pour les "autres lectures", je pense que c'est lié à une catégorie, du coup
> la catégorie (par exemple : Biologie) est déjà indiquée en fin d'articles.
>
> Je pense que cela serait plus esthétique et clair.
>
> Merci, bisou
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/50>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Je laisse tomber https://github.com/ShakePeers/MediaKiki/issues/43 du coup ?

**Comment by vbonhomme** [comment]
voui. les deux vont vers une wikification des box anyway.
besitos

2015-03-14 17:00 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> Je laisse tomber #43 <https://github.com/ShakePeers/MediaKiki/issues/43>
> du coup ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/50#issuecomment-80551547>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
