### ISSUE TITLE
Page accueil : encadrés Articles (publiés, en révision, en brouillon)

### ISSUE THREAD

**Issue by CarolAnnO** [ShakePeers/shakepeers-mediawiki#51]
pouvons-nous créer un modèle pour ces encadrés que l'on peut "wikifier" et autre point : est-ce que l'on peut classer les articles de façon chronologique : dernier soumis/publié/brouillonné, premier sur la liste ? 

Merci, bisou

**Comment by Rudloff** [comment]
Pour l'instant ils sont triés par date de création. Tu voudrais les trier par date de changement d'état, c'est ça ?

**Comment by CarolAnnO** [comment]
Tout à fait :)

**Comment by vbonhomme** [comment]
modifiable en wiki sur le modèle de ShakePeers:Footer ?

**Comment by Rudloff** [comment]
Doublon de #46
