### ISSUE TITLE
TOC invisible ?

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#57]
cf https://shakepeers.org/Aide:FAQ

**Comment by Rudloff** [comment]
Il est masqué dans le CSS. C'était voulu, non ?

**Comment by vbonhomme** [comment]
ben on aimerait l'avoir dans certains cas... genre __FORCETOC__

Le 9 septembre 2015 14:36, Pierre Rudloff <notifications@github.com> a
écrit :

> Il est masqué dans le CSS. C'était voulu, non ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/MediaKiki/issues/57#issuecomment-138895853>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
On doit pouvoir utiliser ça : https://www.mediawiki.org/wiki/Extension:NoTOC

**Comment by Rudloff** [comment]
J'ai mis ça sur beta, il faut mettre `__TOC__` dans un article pour l'afficher.

**Comment by Rudloff** [comment]
Et c'est en prod ;)
