### ISSUE TITLE
svg rendering

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#59]
Une image .svg est cracra [là bas](https://shakepeers.org/Fichier:Morphometrics-approaches.svg) : 
ptet par [ici](https://www.mediawiki.org/wiki/Manual:Image_administration#SVG), un pb de config  ?

**Comment by Rudloff** [comment]
C'est quoi le souci exactement ? Elle a l'air de bien s'afficher chez moi.
