### ISSUE TITLE
boutons marche pas

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#60]
coucou,

les boutons, au moins ceux de LDT permettant de lancer un nouveau fil de discussion ne semblent pas fonctionner, alors qu'ouvrir le lien correspondant fait le job.

**Comment by Rudloff** [comment]
Ça a l'air de fonctionner maintenant.
Tu peux rouvrir si tu revois un truc qui marche pas.
