### ISSUE TITLE
NS supplémentaire : Frigo

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#67]
ola,
je propose de créer (et de m'en occupper) un NS supplémentaire ("Frigo:") pour passer les articles abandonnés, orphelins, etc. à stade brouillon (voire revue)
qu'est-ce t'en dis ?

**Comment by Rudloff** [comment]
Mouais, je sais pas.
Je suis plutôt partisan de la [méthode McDonald's](https://medium.com/@ienjoy/mcdonalds-theory-9216e1c9da7d#.yomy0rpkr) : si on laisse les articles inachevés dans *Brouillon:*, ça peut donner envie à des lecteurs de les reprendre.

**Comment by vbonhomme** [comment]
oui, ou de faire autre chose ;-)
de la balle.

Le 6 janvier 2016 à 13:33, Pierre Rudloff <notifications@github.com> a
écrit :

> Mouais, je sais pas.
> Je suis plutôt partisan de la méthode McDonald's
> <https://medium.com/@ienjoy/mcdonalds-theory-9216e1c9da7d#.yomy0rpkr> :
> si on laisse les articles inachevés dans *Brouillon:*, ça peut donner
> envie à des lecteurs de les reprendre.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/67#issuecomment-169314421>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
