### ISSUE TITLE
Utiliser Composer pour toutes les extensions et les skins

### ISSUE THREAD

**Issue by Rudloff** [ShakePeers/shakepeers-mediawiki#68]

**Comment by Rudloff** [comment]
@vbonhomme On a **beaucoup** d'extensions et ça devenait compliqué à gérer.
Du coup, j'ai commencé à utiliser [Composer](https://getcomposer.org/) pour centraliser la gestion.

J'ai maintenant un fichier avec toutes les extensions qu'on utilise : https://github.com/ShakePeers/shakepeers-mediawiki/blob/develop/composer.json
Il faut donc éviter d'en installer à la main à partir de maintenant pour ne pas créer de conflits.

J'ai déployé ce système sur https://beta.shakepeers.org/Accueil, il faudrait faire un tour pour vérifier que tout fonctionne.

**Comment by vbonhomme** [comment]
de la balle
je pars une semaine mais après ça je teste !

Le 9 janvier 2016 à 20:44, Pierre Rudloff <notifications@github.com> a
écrit :

> @vbonhomme <https://github.com/vbonhomme> On a *beaucoup* d'extensions et
> ça devenait compliqué à gérer.
> Du coup, j'ai commencé à utiliser Composer <https://getcomposer.org/>
> pour centraliser la gestion.
>
> J'ai maintenant un fichier avec toutes les extensions qu'on utilise :
> https://github.com/ShakePeers/shakepeers-mediawiki/blob/develop/composer.json
> Il faut donc éviter d'en installer à la main à partir de maintenant pour
> ne pas créer de conflits.
>
> J'ai déployé ce système sur https://beta.shakepeers.org/Accueil, il
> faudrait faire un tour pour vérifier que tout fonctionne.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/68#issuecomment-170274170>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
