### ISSUE TITLE
daily/weekly email summary of watched pages

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#69]

**Comment by Rudloff** [comment]
Je développe un truc qui fait ça pour un client : https://github.com/Archi-Strasbourg/mediawiki-mail-recentchanges
On peut l'adapter à notre sauce. La vraie question c'est plutôt : est-ce que nos utilisateurs ont envie/besoin de recevoir un mail hebdomadaire ?

**Comment by Rudloff** [comment]
(Du coup je ferme pour l'instant et on rouvrira si le besoin émerge parce qu'on a plein de modifs chaque semaine.)
