### ISSUE TITLE
url articles publiés

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#74]
je pensais qu'on pouvait faire des liens courts avec 

shakepeers.org/85  pour le 85e article, qui redirige vers shakepeers.org/Publication:Le_titre_de_l'article

qu'en penses tu ?

**Comment by Rudloff** [comment]
Tu as une utilisation particulière en tête ?

**Comment by vbonhomme** [comment]
plus court qu'un lien plus archivage temporel clair et permanent

2016-01-08 20:21 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> Tu as une utilisation particulière en tête ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/74#issuecomment-170098354>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Je vois pas bien l'intérêt vu que je vois pas trop dans quelle situation on tape les URL, mais on peut installer ça si tu veux : https://www.mediawiki.org/wiki/Extension:UrlShortener

**Comment by vbonhomme** [comment]
des CVs, des urls en toutes lettres, puis c'est un usage académique.

Le 8 janvier 2016 à 20:39, Pierre Rudloff <notifications@github.com> a
écrit :

> Je vois pas bien l'intérêt vu que je vois pas trop dans quelle situation
> on tape les URL, mais on peut installer ça si tu veux :
> https://www.mediawiki.org/wiki/Extension:UrlShortener
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/74#issuecomment-170102814>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Pas besoin d'extension en fait, j'ai bricolé ça dans l'entête des articles.

**Comment by vbonhomme** [comment]
comment tu fais poulet ?

2016-01-10 17:23 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> Pas besoin d'extension en fait, j'ai bricolé ça dans l'entête des articles.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/74#issuecomment-170364659>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Chaque article à un ID et tu peux donc l'utiliser pour accéder à l'article : https://shakepeers.org/?curid=836
Du coup, j'ai modifié *Modèle:BandeauHeaderRévision* pour y inclure une URL de ce format : 
```{{SERVER}}?curid={{PAGEID}}```

**Comment by vbonhomme** [comment]
voui mais l'vantage c'était de les déclarer dans l'ordre de publication :-s

Le 10 janvier 2016 à 20:28, Pierre Rudloff <notifications@github.com> a
écrit :

> Chaque article à un ID et tu peux donc l'utiliser pour accéder à l'article
> : https://shakepeers.org/?curid=836
> Du coup, j'ai modifié *Modèle:BandeauHeaderRévision* pour y inclure une
> URL de ce format :
> {{SERVER}}?curid={{PAGEID}}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/74#issuecomment-170383742>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Hum, je vois pas trop comment faire.
Ça changerait quoi concrètement ?

**Comment by vbonhomme** [comment]
ben c juste que chaque article publié a un raccourci en shakepeers.org/nnn
avec nnn incrémenté pour chaque article

2016-01-10 21:33 GMT+00:00 Pierre Rudloff <notifications@github.com>:

> Hum, je vois pas trop comment faire.
> Ça changerait quoi concrètement ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/74#issuecomment-170396270>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Nan je veux dire : ça changerait quoi que seuls les articles publiés aient un numéro ?

**Comment by vbonhomme** [comment]
ben précisément ça marquerait qu'ils sont publiés (entres autres choses).
et faudrait ptet renforcer le côté "pas encore publié, potentiellement
merdique" selon qqs stagiaires...

2016-01-11 22:07 GMT+00:00 Pierre Rudloff <notifications@github.com>:

> Nan je veux dire : ça changerait quoi que seuls les articles publiés aient
> un numéro ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/74#issuecomment-170706637>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
