### ISSUE TITLE
Enlever NUMBEROFVIEWS

### ISSUE THREAD

**Issue by Rudloff** [ShakePeers/shakepeers-mediawiki#76]
Le mot magique *NUMBEROFVIEWS* n'existe plus depuis MediaWiki 1.25, il faudrait le retirer là où il est utilisé.

**Comment by vbonhomme** [comment]
ce serait tout de même souhaitable d'avoir un compteur de vues ?! si possible par page, au moins pour révision, publication ?

**Comment by vbonhomme** [comment]
done

**Comment by Rudloff** [comment]
SI tu veux un compteur de vues pour nous en interne, on peut mettre un truc comme ça : https://www.mediawiki.org/wiki/Extension:Google_Analytics_Integration

**Comment by vbonhomme** [comment]
et un public ?

2016-01-20 11:17 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> SI tu veux un compteur de vues pour nous en interne, on peut mettre un
> truc comme ça :
> https://www.mediawiki.org/wiki/Extension:Google_Analytics_Integration
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/76#issuecomment-173159639>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Il n'y a pas de remplacement apparemment (et de toute façon c'est jamais fiable ces trucs).
