### ISSUE TITLE
veaction bugué

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#77]

**Comment by Rudloff** [comment]
J'ai mis [Parsoid](https://www.mediawiki.org/wiki/Parsoid) à jour et ça semble de nouveau fonctionner.
Pense à vider le cache de ton navigateur.

**Comment by vbonhomme** [comment]
faudrait ptet passer le crayon en veedit et modifier en edit ? ça me
perturbe (et pas le seul) que les deux soient pas sur le même niveau.
d'ailleurs ces boutons me perturbe un peu

2016-01-14 22:43 GMT+00:00 Pierre Rudloff <notifications@github.com>:

> J'ai mis Parsoid <https://www.mediawiki.org/wiki/Parsoid> à jour et ça
> semble de nouveau fonctionner.
> Pense à vider le cache de ton navigateur.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/77#issuecomment-171805433>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
