### ISSUE TITLE
MAJ après publication article

### ISSUE THREAD

**Issue by atulebamboo** [ShakePeers/shakepeers-mediawiki#78]
Hello,

Plusieurs pages ne se sont pas mises à jour suite à la publication du premier article.

- page d'accueil, qui liste toujours 2 contributions candidates à la publication et  0 publiée
- https://shakepeers.org/Publication

**Comment by vbonhomme** [comment]
parce qu'il y a un lag, observé en formation, de ~30min je dirais. du à
DynamicPageList
dans le footer, c'est updaté mais ça repose sur autre chose


Le 14 janvier 2016 à 19:46, Arthur Escalas <notifications@github.com> a
écrit :

> Hello,
>
> Plusieurs pages ne se sont pas mises à jour suite à la publication du
> premier article
>
>    - page d'accueil, qui liste toujours 2 contributions candidates à la
>    publication et 0 publiée
>    - https://shakepeersorg/Publication
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/78>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Hello,

Il y a un cache qui permet d'améliorer les performances, mais introduit du coup un délai.
On peut purger le cache d'une page en suivant ces instructions : https://www.mediawiki.org/wiki/Manual:Purge

Je suis d'avis de garder le cache, pour ne pas ralentir le site.

**Comment by atulebamboo** [comment]
My bad

**Comment by vbonhomme** [comment]
oui tèrs bien le cache. pas mort d'humain

2016-01-15 4:07 GMT+00:00 Arthur Escalas <notifications@github.com>:

> My bad
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/78#issuecomment-171867100>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
