### ISSUE TITLE
Ajouter un composer.json à toutes les extensions.

### ISSUE THREAD

**Issue by Rudloff** [ShakePeers/shakepeers-mediawiki#81]
Suite à  #68, ça serait bien que toutes les extensions ait un fichier composer.json valide.
Je vais proposer des patchs à MediaWiki.

**Comment by Rudloff** [comment]
Extensions à patcher : 
* BetaFeatures
* bootstrap-skin
* CategoryTree
* CheckUser
* Cite
* ConfirmEdit
* Description2
* Duplicator
* Echo
* EtherpadLite
* EventLogging
* GuidedTour
* InputBox
* intersection
* LabeledSectionTransclusion
* LiquidThreads
* Lockdown
* MaintenanceShell
* Math
* Nuke
* OpenGraphMeta
* ParserFunctions
* Parsoid
* PdfHandler
* Preloader
* Renameuser
* RSS
* TextExtracts
* UserMerge
* Variables
* VisualEditor
* WikiArticleFeeds
* WikiEditor

**Comment by Rudloff** [comment]
Patch proposé pour LiquidThreads : https://phabricator.wikimedia.org/T123363

**Comment by Rudloff** [comment]
Bug pour VisualEditor : https://phabricator.wikimedia.org/T135914

**Comment by Rudloff** [comment]
Les développeurs de MediaWiki ne sont pas très fans de Composer, donc j'ai bricolé un truc pour contourner le problème : https://mwpackagist.netlib.re/

**Comment by vbonhomme** [comment]
voué j'ai vu/lu ça. bravo !

2016-05-22 17:12 GMT+02:00 Pierre Rudloff <notifications@github.com>:

> Closed #81 <https://github.com/ShakePeers/shakepeers-mediawiki/issues/81>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/81#event-668235370>
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
