### ISSUE TITLE
Checkbox Garder ma session active ne s'affiche pas toujours

### ISSUE THREAD

**Issue by Rudloff** [ShakePeers/shakepeers-mediawiki#82]
![connexion_ _shakepeers_-_2016-01-14_23 54 40](https://cloud.githubusercontent.com/assets/840125/12340288/3d9850a4-bb1a-11e5-8889-f3c932b8efb5.png)
Parfois la checkbox ne s'affiche pas.

**Comment by vbonhomme** [comment]
c'est un problème de checkbox global et pas que sur ce lien (j'imagine que
c'était le sens de ton message)

2016-01-14 22:55 GMT+00:00 Pierre Rudloff <notifications@github.com>:

> [image: connexion_ _shakepeers_-_2016-01-14_23 54 40]
> <https://cloud.githubusercontent.com/assets/840125/12340288/3d9850a4-bb1a-11e5-8889-f3c932b8efb5.png>
> Parfois la checkbox ne s'affiche pas.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/82>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Alors en fait MediaWiki a changé la structure HTML de certaines checkboxes, ce qui les rend difficile à styliser. Du coup, pour celles-là j'affiche une checkbox native basique (https://github.com/ShakePeers/shakepeers-mediawiki-skin/commit/6bf70bfba93bdfbb6ff8bcec375dd49f2f8534b1).
Par contre, j'ai pas le temps de mettre ça en production pour le moment.
