### ISSUE TITLE
Maydee: pb de Captcha, donc création de compte impossible

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#83]
avec l'erreur suivante: `Fatal error: Call to undefined method ReCaptchaNoCaptcha::logStatusError() in /home/shakepeers/mediawiki/extensions/ConfirmEdit/ReCaptchaNoCaptcha/ReCaptchaNoCaptcha.class.php on line 88`

le captcha ne s'affiche pas tout court ceci dit...

**Comment by Rudloff** [comment]
C'est un bug dans la dernière version stable de l'extension ConfirmEdit.
Je suis passé sur la master et ça a l'air d'être corrigé.

**Comment by vbonhomme** [comment]
ça marche.
tu es une personne incroyable.
<3

2016-02-09 20:47 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> Closed #83 <https://github.com/ShakePeers/shakepeers-mediawiki/issues/83>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/83#event-544833600>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
