### ISSUE TITLE
notif par mail

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#84]
ne semble pas fonctionner.
cf https://shakepeers.org/Sp%C3%A9cial:Pr%C3%A9f%C3%A9rences#mw-prefsection-echo

**Comment by Rudloff** [comment]
T'as testé quoi ?
Je me suis posté un message sur ma page de discussion avec un compte de test et j'ai bien reçu un mail pour me prévenir.

**Comment by vbonhomme** [comment]
je ne reçois juste rien du tout !
et tout est coché chez moi

Le 10 février 2016 à 11:08, Pierre Rudloff <notifications@github.com> a
écrit :

> T'as testé quoi ?
> Je me suis posté un message sur ma page de discussion avec un compte de
> test et j'ai bien reçu un mail pour me prévenir.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/84#issuecomment-182290012>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Je t'ai posté un message sur ta page de discussion et je vois bien un message parti vers toi dans les logs.

**Comment by vbonhomme** [comment]
de toi, je reçois.
pas de mes articles suivis. bizarre, mais pas très grave.
merci pour ton aide.


2016-02-10 11:15 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> Je t'ai posté un message sur ta page de discussion et je vois bien un
> message parti vers toi dans les logs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/84#issuecomment-182293574>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
#close

Le 10 février 2016 à 11:22, Vincent Bonhomme <bonhomme.vincent@gmail.com> a
écrit :

> de toi, je reçois.
> pas de mes articles suivis. bizarre, mais pas très grave.
> merci pour ton aide.
>
>
> 2016-02-10 11:15 GMT+01:00 Pierre Rudloff <notifications@github.com>:
>
>> Je t'ai posté un message sur ta page de discussion et je vois bien un
>> message parti vers toi dans les logs.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/84#issuecomment-182293574>
>> .
>>
>
>
>
> --
> vincentbonhomme.fr <http://www.vincentbonhomme.fr>
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
