### ISSUE TITLE
depuis *_talk:... retour vers _:...

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#87]
à partir de la page de discussion d'une page donnée, le retour n'est actuellement pas simple...

**Comment by Rudloff** [comment]
J'ai bricolé un truc dans le thème qui remplace le bouton discussion par un bouton de retour. Tu peux tester ça sur beta.
Dis-moi si ça te va.

**Comment by vbonhomme** [comment]
c'est nickel ! merci

2016-03-17 0:11 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> J'ai bricolé un truc dans le thème qui remplace le bouton discussion par
> un bouton de retour. Tu peux tester ça sur beta.
> Dis-moi si ça te va.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/87#issuecomment-197597107>
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
