### ISSUE TITLE
Éditeur visuel par défaut

### ISSUE THREAD

**Issue by Rudloff** [ShakePeers/shakepeers-mediawiki#89]
@vbonhomme Comme tu l'as proposé dans https://github.com/ShakePeers/shakepeers-mediawiki/issues/77#issuecomment-171902239, j'ai inversé la position de _Modifier_ et _Modifier le wikicode_ sur beta.
Ça te va comme ça ou tu veux qu'on mette carrément les deux côte à côte (ça serait un peu chargé) ?

**Comment by vbonhomme** [comment]
c'est parfait comme ça je pense. Qu'est-ce t'en dis toi ?
D'ailleurs, je serais assez pour mettre ce qu'il y a dans la bulle (i) dans
la clé à molette ? d'autant qu'avoir plus de 3-4 liens sera surtout pour
les éditeurs/admin non ?

Le 16 mars 2016 à 22:35, Pierre Rudloff <notifications@github.com> a écrit :

> @vbonhomme <https://github.com/vbonhomme> Comme tu l'as proposé dans #77
> (comment)
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/77#issuecomment-171902239>,
> j'ai inversé la position de *Modifier* et *Modifier le wikicode* sur beta.
> Ça te va comme ça ou tu veux qu'on mette carrément les deux côte à côte
> (ça serait un peu chargé) ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/89>
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Je me suis fait la même réflexion quand j'ai modifié le truc. Je vais voir ce que ça donne.

**Comment by Rudloff** [comment]
J'ai tout regroupé dans _Outils_ (sur beta) et effectivement ça fait que 4 liens quand on est pas admin donc c'est suffisant.

**Comment by vbonhomme** [comment]
Diantre on respire.
Je me demande si il ne faudrait pas afficher les boutons pour les non
logués aussi ?
Ok on a les bandeux, mais ptet que ce serait plus hameçonnant ? J'en sais
rien. et me range à ton avis.

2016-03-17 20:00 GMT+01:00 Pierre Rudloff <notifications@github.com>:

> Closed #89 <https://github.com/ShakePeers/shakepeers-mediawiki/issues/89>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/89#event-593905472>
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
Oui, pas de raison de pas l'afficher, surtout que maintenant ça fait que deux boutons.
