### ISSUE TITLE
Menu ShakePeers

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#90]
au moins les 4 premiers items du menu "help v" de SO ( http://stackoverflow.com/tour ) pourraient être adaptés pour naviguer/guider dans shakepeers. actuellement, c'est un peu confus.

**Comment by vbonhomme** [comment]
Voir proposition [ici](https://shakepeers.org/Aide:Th%C3%A8meShakePeers/Interface)

**Comment by Rudloff** [comment]
La proposition me semble pas mal. J'essaie de mettre ça sur beta dès que j'ai un peu de temps.

**Comment by Rudloff** [comment]
2 petites remarques tout de même :
* Ça me parait bien de garder Accueil dans le menu principal, les gens ne savent pas forcément qu'on peut cliquer sur le logo.
* Je garderais Brouillons/En révision/Publiés dans le menu Articles pour ne pas surprendre les visiteurs (on arrive sur des pages qui listent des articles, pas qui déclenche des actions).

**Comment by Rudloff** [comment]
@vbonhomme J'ai modifié les menus sur beta si te veux jeter un œil.

**Comment by vbonhomme** [comment]
c'est de la balle !

"Contribuer" un peu niché et tt nulle part "Écrire", "Relire", "Lire". ptet
pas du ressort de ce menu.

2016-07-02 23:06 GMT+02:00 Pierre Rudloff <notifications@github.com>:

> @vbonhomme <https://github.com/vbonhomme> J'ai modifié les menus sur beta
> si te veux jeter un œil.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/90#issuecomment-230122061>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEgoFvM_cUu7oS76NS3AON-liyHjzwXlks5qRtLZgaJpZM4H3CwF>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
J'ai mis ça en production.
