### ISSUE TITLE
mass delete spammers

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/shakepeers-mediawiki#95]
merger des [dizaines de spammers](https://shakepeers.org/index.php?title=Sp%C3%A9cial:Liste_des_utilisateurs&offset=&limit=500&username=&group=&creationSort=1&desc=1) n'est pas l'opération la plus rigolote. pas de solution vraiment satisfaisant pour mass deleter/merge.

ne pourrait-on pas, passer plusieurs noms d'utilisateurs séparés par des virgules dans le champ "utilisateur à fusionner" ?

**Comment by Rudloff** [comment]
Je peux installer ça : https://www.mediawiki.org/wiki/Extension:BlockAndNuke
(mais c'est à manier avec des pincettes)

**Comment by Rudloff** [comment]
C'est en place : https://shakepeers.org/Sp%C3%A9cial:Blockandnuke
Mais ça liste que les utilisateurs récents en fait donc pas hyper utile dans l'immédiat.

**Comment by Rudloff** [comment]
J'ai fait un gros tri à la main, on devrait y voir plus clair.
