### ISSUE TITLE
MediaWiki 1.27

### ISSUE THREAD

**Issue by Rudloff** [ShakePeers/shakepeers-mediawiki#97]
La version 1.27 est sortie, il faut voir si c'est compliqué de migrer.

**Comment by Rudloff** [comment]
@vbonhomme L'extension [Lockdown](https://www.mediawiki.org/wiki/Extension:Lockdown) ne fonctionne pas avec MW 1.27 pour l'instant.
On s'en sert de cette extension ?

**Comment by vbonhomme** [comment]
je crois pas

2016-06-29 11:01 GMT+02:00 Pierre Rudloff <notifications@github.com>:

> @vbonhomme <https://github.com/vbonhomme> L'extension Lockdown
> <https://www.mediawiki.org/wiki/Extension:Lockdown> ne fonctionne pas
> avec MW 1.27 pour l'instant.
> On s'en sert de cette extension ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/97#issuecomment-229298875>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEgoFqP682D6gOLGounjn6ahJJNk16uHks5qQjR9gaJpZM4JA6je>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
OK je la désactive alors (c'est cool c'est l'occasion de faire le tri dans nos 50 extensions ^^).

**Comment by vbonhomme** [comment]
voué sacré merdier
LocalSettings aussi c'est un peu le chantier

2016-06-29 11:17 GMT+02:00 Pierre Rudloff <notifications@github.com>:

> OK je la désactive alors (c'est cool c'est l'occasion de faire le tri dans
> nos 50 extensions ^^).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ShakePeers/shakepeers-mediawiki/issues/97#issuecomment-229302766>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEgoFk392qjHzG-NtwW98db1Hle9maCsks5qQjhHgaJpZM4JA6je>
> .
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by Rudloff** [comment]
HeaderFooter a également un souci avec MW 1.27 (et celle là clairement on l'utilise) : https://github.com/enterprisemediawiki/HeaderFooter/issues/11

**Comment by Rudloff** [comment]
J'ai installé MW 1.27 sur beta.
@vbonhomme Si tu veux faire un tour pour vérifier que tout fonctionne.
